workflows:
  debug-apk:
    name: Build APK (Debug)
    environment:
      vars:
        EXPO_DEBUG: 'true'
      flutter: null
      xcode: null
      node: 20.9.0
      yarn: false
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Build APK (Debug)
        script: expo build:android -t apk --non-interactive
    artifacts:
      - build/**/*.apk
    cache:
      cache_paths:
        - node_modules
