workflows:
  debug-apk:
    name: Build APK (Debug)
    environment:
      node: 20.9.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install  # genera package-lock.json para que npm no falle:contentReference[oaicite:2]{index=2}
      - name: Build Android APK
        script: |
          npm run build:android  # ejecuta prebuild de Expo y assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    cache:
      cache_paths:
        - node_modules
        - android/.gradle
