workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: 18.16.0
      vars:
        EXPO_USE_DEV_CLIENT: false
    scripts:
      # 1. Instala dependencias de JS
      - npm install

      # 2. Genera la carpeta android sin instalar de nuevo
      - npx expo prebuild --platform android --no-install

      # 3. Parchea android/build.gradle para forzar Kotlin jvmTarget = 17
      - sed -i '' '/android {/a\
          \ \ \ \ kotlinOptions { jvmTarget = "17" }' android/build.gradle

      # 4. Opcional: configura el toolchain Java 17 en Kotlin DSL
      - sed -i '' '/plugins {/a\
          \kotlin { jvmToolchain(17) }' android/build.gradle

      # 5. Ensambla el APK en release
      - cd android && ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
