workflows:
  debug-apk:
    name: Build APK (Debug)
    environment:
      node: 20.9.0
      java: 17
    scripts:
     - name: Build Android APK
        script: npm run codemagic:android
    artifacts:
      - android/app/build/outputs/**/*.apk
    cache:
      cache_paths:
        - node_modules
        - android/.gradle
