workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: 18.16.0
      vars:
        EXPO_USE_DEV_CLIENT: false
    scripts:
      # 1. Instala dependencias
      - npm install

      # 2. Genera el proyecto nativo Android (prebuild) sin reinstalar en android/
      - npx expo prebuild --platform android --no-install

      # 3. Fija kotlinOptions.jvmTarget a 17 inyectándolo en gradle.properties del proyecto Android
      #    Esto evita el error de incompatibilidad JVM 11 vs 17
      - echo 'kotlin.compiler.jvmTarget=17' >> android/gradle.properties

      # 4. Compila el APK
      - cd android && ./gradlew assembleRelease

    artifacts:
      # Este patrón recoge cualquier APK generado en outputs/
      - android/app/build/outputs/**/*.apk
