workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable
    scripts:
      - echo "🛠️  Compilando APK de Android…"
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

triggers:
  push:
    branches:
      - main
