workflows:
  android-release:
    name: Android Release
    triggers:
      - push:
          branches: [ main ]
    scripts:
      - name: Prebuild
        script: npx expo prebuild --platform android --no-install
      - name: Assemble release
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
