workflows:
  debug-apk:
    name: Build APK (Debug)
    environment:
      node: 20.9.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npm run build:android
    artifacts:
      - android/app/build/outputs/**/*.apk
    cache:
      cache_paths:
        - node_modules
        - android/.gradle
