workflows:
  debug-apk:
    name: Build APK (Debug)
    environment:
      # Versión de Node y Java que usará Codemagic
      node: 20.9.0
      java: 11
    scripts:
      # Instala las dependencias
      - name: Install dependencies
        script: |
          npm install

      # Ejecuta el prebuild de Expo y compila el APK
      - name: Build Android APK
        script: |
          npm run build:android

    artifacts:
      # Recoge los APK generados
      - android/app/build/outputs/**/*.apk

    cache:
      cache_paths:
        - node_modules
        - android/.gradle
