workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: 18.16.0
      vars:
        EXPO_USE_DEV_CLIENT: false
    scripts:
      - npm install
      - npx expo prebuild --platform android --no-install

      # eliminar classifier de splash-screen
      - sed -i.bak "/classifier =/d" node_modules/expo-splash-screen/android/build.gradle
      - sed -i.bak "/artifact(androidSourcesJar)/d" node_modules/expo-splash-screen/android/build.gradle

      # forzar versiones de SDK
      - echo "android.compileSdkVersion=33" >> android/gradle.properties
      - echo "android.targetSdkVersion=33"  >> android/gradle.properties
      - echo "android.minSdkVersion=24"     >> android/gradle.properties

      # Kotlin jvmTarget = 17
      - echo "kotlin.compiler.jvmTarget=17" >> android/gradle.properties

      - cd android && ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
